name: Docker Publish 

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          DOCKER_TAG=$(echo ${{ github.event.release.tag_name }} | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._')
          docker build . --file Dockerfile --tag ajayosak/aurora:${DOCKER_TAG}
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push ajayosak/aurora:${DOCKER_TAG}
          docker tag ajayosak/aurora:${DOCKER_TAG} ajayosak/aurora:latest
          docker push ajayosak/aurora:latest
